computablelabs/ffa-frontend

package.json, src/global.d.ts, src/util/Metamask.ts
=> define Transaction interface globally. implement send.

src/components/listing/FileUploader.vue, src/functionModules/components/FileUploaderModule.ts, tests/unit/functionModules/components/FileUploaderModule.spec.ts
=> File uploader refactor

package.json, src/functionModules/components/FileListerModule.ts
=> enable istanbul code coverage

jest.config.js, src/App.vue, src/components/ui/Navigation.vue, src/interfaces/vuex/FfaProcessModule.ts, src/util/Metamask.ts, src/views/List.vue, src/vuexModules/UploadModule.ts, tests/unit/functionModules/components/FileUploaderModule.spec.ts, tests/unit/modules/UploadModule.spec.ts
=> Replace state.publicKey in favor of ethereum.selectedAddress

src/components/listing/FileLister.vue, src/components/listing/FileMetadata.vue, src/components/listing/FileUploader.vue, src/functionModules/components/FileListerModule.ts, src/functionModules/components/FileMetadataModule.ts, src/functionModules/components/FileUploaderModule.ts, src/functionModules/protocol/ListingModule.ts, src/util/Metamask.ts, src/views/ListDrawer.vue, src/vuexModules/ListModule.ts, src/vuexModules/UploadModule.ts, tests/unit/components/listing/FileMetadata.spec.ts, tests/unit/functionModules/components/FileListerModule.spec.ts, tests/unit/functionModules/components/FileMetadataModule.spec.ts, tests/unit/functionModules/components/FileUploaderModule.spec.ts, tests/unit/modules/ListModule.spec.ts, tests/unit/modules/UploadModule.spec.ts, tests/unit/views/ListDrawer.spec.ts
=> Completes #114

src/App.vue, src/components/listing/FileMetadata.vue, src/components/listing/FileUploader.vue, src/functionModules/components/FileUploaderModule.ts, src/vuexModules/UploadModule.ts, tests/unit/functionModules/components/FileUploaderModule.spec.ts
For #116. I'm getting a weird error. `TypeError: Cannot read property 'getters' of undefined`. Don't want to spend too much time debugging this- Will hold off for now, just wanted to let you know.
=> Getting Error. Refactor enableEthereum, refactor tests

src/models/FfaListing.ts, src/vuexModules/FfaListingsModule.ts, src/vuexModules/ListModule.ts, src/vuexModules/UploadModule.ts, tests/unit/field-validators/TitleFieldValidator.spec.ts, tests/unit/module-validators/UploadModuleValidator.spec.ts, tests/unit/modules/FfaListingsModule.spec.ts, tests/unit/modules/ListModule.spec.ts, tests/unit/modules/UploadModule.spec.ts
=> Ffa listing

src/components/listing/FileMetadata.vue, src/components/listing/FileUploader.vue, src/views/FfaListingDetails.vue, src/views/List.vue, tests/unit/components/listing/FileUploader.spec.ts, tests/unit/views/FfaListingDetails.spec.ts, tests/unit/views/List.spec.ts
=> Adding an Eth-Loader

jest.config.js, package.json, src/App.vue, src/components/task/TaskPollerManager.vue, src/functionModules/components/TaskPollerManagerModule.ts, src/functionModules/datatrust/DatatrustModule.ts, src/functionModules/localStorage/LocalStorageModule.ts, src/interfaces/Storeable.ts, src/models/DatatrustTask.ts, src/models/DatatrustTaskDetails.ts, src/models/TaskPoller.ts, src/store.ts, src/util/Config.ts, src/views/FfaListedView.vue, src/vuexModules/DatatrustTaskModule.ts, src/vuexModules/FfaListingsModule.ts, src/vuexModules/validators/TitleFieldValidator.ts, tests/unit/components/listing/FfaListingsComponent.spec.ts, tests/unit/components/task/TaskPollerManager.spec.ts, tests/unit/field-validators/TitleFieldValidator.spec.ts, tests/unit/functionModules/components/TaskPollerManagerModule.spec.ts, tests/unit/functionModules/datatrust/DatatrustModule.spec.ts, tests/unit/functionModules/localStorage/LocalStorageModule.spec.ts, tests/unit/module-validators/UploadModuleValidator.spec.ts, tests/unit/vuexModules/DatatrustTaskModule.spec.ts, tests/unit/vuexModules/FfaListingsModule.spec.ts, yarn.lock
=> First cut of the task poller with limited integration. Needs more specs.

src/components/ui/Status.vue, src/components/voting/VerticalSubway.vue, src/components/voting/VotingDetails.vue, src/components/voting/VotingInterface.vue, src/functionModules/components/PurchaseProcessModule.ts, src/functionModules/ethereum/EthereumModule.ts, src/functionModules/protocol/MarketTokenContractModule.ts, src/views/FfaCandidateView.vue, src/views/drawers/VotingDrawer.vue, tests/unit/components/ui/ProcessButton.spec.ts, tests/unit/components/voting/VerticalSubway.spec.ts, tests/unit/functionModules/components/PurchaseProcessModule.spec.ts, tests/unit/views/FfaCandidateView.spec.ts
=> Refactor FfaCandidateView + add specs for ProcessButton

src/components/purchase/ApproveSpendingStep.vue, src/components/purchase/Erc20TokenStep.vue, src/components/purchase/PurchaseListingStep.vue, src/components/voting/VerticalSubway.vue, src/components/voting/VotingInterface.vue, src/functionModules/components/FileListerModule.ts, src/functionModules/components/PurchaseProcessModule.ts, src/functionModules/ethereum/EthereumModule.ts, src/functionModules/protocol/DatatrustContractModule.ts, src/functionModules/protocol/EtherTokenContractModule.ts, src/functionModules/protocol/ListingContractModule.ts, src/functionModules/protocol/MarketTokenContractModule.ts, src/functionModules/protocol/ParameterizerContractModule.ts, src/functionModules/protocol/VotingContractModule.ts, src/functionModules/views/FfaListingViewModule.ts, tests/unit/components/purchase/PurchaseProcess.spec.ts, tests/unit/functionModules/components/PurchaseProcessModule.spec.ts, tests/unit/functionModules/views/FfaListingViewModule.spec.ts, tests/unit/views/FfaCandidateView.spec.ts, tests/unit/views/FfaListedView.spec.ts, tests/unit/views/drawers/PurchaseDrawer.spec.ts
=> Remove transactOpts from protocol functions and function invocations

README.md, src/components/listing/NewListingProcess.vue, src/components/listing/NewListingProcessPresentation.vue, tests/unit/components/listing/NewListingProcessPresentation.spec.ts
Address pr comments and https://github.com/computablelabs/ffa-frontend/issues/264
=> Rw small fixes

src/components/purchase/ApproveSpendingStep.vue, src/components/purchase/Erc20TokenStep.vue, src/components/purchase/PurchaseListingStep.vue, src/components/purchase/PurchaseProcess.vue, src/components/ui/ProcessButton.vue, src/functionModules/components/PurchaseProcessModule.ts, src/router.ts, src/views/FfaListedView.vue, tests/unit/components/listing/NewListingProcessPresentation.spec.ts, tests/unit/components/purchase/ApproveSpendingStep.spec.ts, tests/unit/components/purchase/Erc20TokenStep.spec.ts, tests/unit/components/purchase/PurchaseProcess.spec.ts, tests/unit/field-validators/TitleFieldValidator.spec.ts, tests/unit/functionModules/ethereum/EthereumModule.spec.ts, tests/unit/module-validators/UploadModuleValidator.spec.ts, tests/unit/views/FfaListedView.spec.ts, tests/unit/views/drawers/PurchaseDrawer.spec.ts
=> Light purchase flow refactor + specs

src/components/ui/TabsHeader.vue, src/views/FfaCandidateView.vue, src/views/FfaListedView.vue, tests/unit/views/FfaListedView.spec.ts
#318
* Pulled out tabs header from `FfaCandidateView` to use in `FfaListedView`
* Added tabs
* Tests
* Will work on drawers in another ticket
=> Mm challenge0

src/components/supportWithdraw/SupportErc20TokenStep.vue, src/components/supportWithdraw/WithdrawFromCooperative.vue, src/functionModules/ethereum/EthereumModule.ts, src/router.ts, src/views/FfaListedView.vue, src/views/Support.vue, tests/unit/functionModules/ethereum/EthereumModule.spec.ts, tests/unit/views/FfaListedView.spec.ts, tests/unit/views/Support.spec.ts
=> add requiresParameters to support view

src/components/purchase/ApproveSpendingStep.vue, src/components/voting/VotingInterface.vue, src/functionModules/components/TaskPollerManagerModule.ts, src/functionModules/components/VotingProcessModule.ts, src/models/ChallengeStep.ts, src/models/DatatrustTaskDetails.ts, src/models/Events.ts, src/router.ts, src/store.ts, src/util/Constants.ts, src/views/FfaListedView.vue, src/views/drawers/ChallengeDrawer.vue, src/vuexModules/ChallengeModule.ts, src/vuexModules/VotingModule.ts, tests/unit/components/supportWithdraw/SupportProcess.spec.ts, tests/unit/views/FfaListedView.spec.ts, tests/unit/views/drawers/ChallengeDrawer.spec.ts
=> Mm challenge1

src/main.ts
=> New vue router configuration

src/components/voting/VerticalSubway.vue, src/components/voting/VotingDetails.vue, src/functionModules/components/TaskPollerManagerModule.ts, src/models/DatatrustTaskDetails.ts, src/views/FfaListedView.vue, src/views/drawers/ChallengeDrawer.vue, src/vuexModules/VotingModule.ts, tests/unit/components/ui/Drawer.spec.ts, tests/unit/views/FfaListedView.spec.ts
#319 
#321 
Add specs for these issues.
=> Mm challenge2.5

src/components/voting/VerticalSubway.vue, src/views/FfaListedView.vue, tests/unit/views/FfaListedView.spec.ts
Wrote some tests to make sure this gets caught
=> Fixes #398

src/components/supportWithdraw/EthereumToMarketToken.vue, src/components/supportWithdraw/YourTokens.vue, src/functionModules/components/SupportWithdrawProcessModule.ts, src/functionModules/ethereum/EthereumModule.ts, src/functionModules/metamask/MetamaskModule.ts, src/functionModules/protocol/EtherTokenContractModule.ts, src/functionModules/protocol/ReserveContractModule.ts, tests/unit/components/supportWithdraw/EthereumToMarketToken.spec.ts, tests/unit/functionModules/ethereum/EthereumModule.spec.ts
=> Km support bug

src/components/voting/VotingDetails.vue, src/views/FfaCandidateView.vue, src/views/FfaListedView.vue, tests/unit/components/voting/VotingDetails.spec.ts
Created another pr to fix rebase issues.
=> Fixes #506 - Render drawer buttons disabled when drawer is processing

src/components/listing/FfaListingsComponent.vue, src/functionModules/views/ListingsModule.ts, src/views/Listings.vue
* Made user listing work
* Parallelized listings, candidates API call
=> Fixes #507 -- mm user listing

src/assets/style/ui/drawer-message.sass, src/assets/style/ui/drawer.sass, src/assets/style/ui/process-button.sass, src/components/ui/ProcessButton.vue, src/components/voting/CastVoteStep.vue, src/components/voting/VotingApproveSpendingStep.vue, src/components/voting/VotingProcess.vue, src/views/drawers/ChallengeDrawer.vue, tests/unit/components/supportWithdraw/EthereumToMarketToken.spec.ts
I tried stacking them but the layout was illegible.  Left the conditional rendering for the steps in `VotingProcess`.
=> Fixes #556

.travis.yml, Dockerfile, Dockerfile_auth.dockerfile, conf/nginx_auth.conf, scripts/deploy_with_auth.sh
and Fix hard-coded tags in docker build
=> Add auth to mainnet deploy

src/functionModules/datatrust/DatatrustModule.ts, src/util/Paths.ts, tests/unit/components/supportWithdraw/WithdrawProcess.spec.ts, tests/unit/functionModules/components/SupportWithdrawProcessModule.spec.ts, tests/unit/functionModules/datatrust/DatatrustModule.spec.ts
Reverts computablelabs/ffa-frontend#601
=> Revert "remove /application from candidates path"

package.json
=> Add NODE_ENV=production for rinkeby and mainnet

src/functionModules/components/PurchaseProcessModule.ts, src/functionModules/protocol/DatatrustContractModule.ts, tests/unit/functionModules/components/PurchaseProcessModule.spec.ts
I removed the byte_requested check as the backend no longer makes thats check. Made sure to test this manually.
=> mm - fixes #688 - Add filtering for delivered event

src/functionModules/components/PurchaseProcessModule.ts, src/functionModules/protocol/DatatrustContractModule.ts, tests/unit/functionModules/components/PurchaseProcessModule.spec.ts
Reverts computablelabs/ffa-frontend#691
=> Revert "Push to Rinkeby"

src/App.vue, src/components/ui/Navigation.vue, src/models/NavigationView.ts, tests/unit/components/ui/Navigation.spec.ts
=> mm - fixes #708 - Conditional nav bar rendering

package.json, public/index.html, src/App.vue, src/global.d.ts, yarn.lock
=> first cut of amplitude integration
